---
# tasks file for apache
- name: install apache
  apt: 
      name: apache2 
      state: latest
  become: yes   
- name: Copying the demo file
  template: src=/home/ubuntu/index.html dest=/var/www/html
              owner=ubuntu group=ubuntu mode=644
  become: yes
- name: restart apache2
  service: 
      name: apache2 
      state: restarted 
      enabled: yes
  become: yes
