---
- hosts: webservers
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: Install Apache
      apt: name=apache2 state=present
    - name: Copying the demo file
      template: src=/home/ubuntu/index.html dest=/var/www/html
              owner=ubuntu group=ubuntu mode=644
  
