---
- hosts: webservers  
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: install packages
      apt: name={{item}} state=latest
      with_items:
          - tree
          - telnet
          - vim
          - ufw   
