---
- hosts: webservers 
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: Copy ansible public key to manage host 
      authorized_key:
         user: ubuntu
         state: present
         key: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"
